parameters:
    developer.name: test

imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"        

web_profiler:
    toolbar: false
    intercept_redirects: false
