trismegiste_oauth:
    resource: "@TrismegisteOAuthBundle/Resources/config/routing.xml"
    prefix:   /

trismegiste_front:
    resource: "@TrismegisteFrontBundle/Resources/config/routing.xml"
    prefix:   /
    