trismegiste_front:
    resource: "@TrismegisteFrontBundle/Resources/config/routing.xml"
    prefix:   /

trismegiste_logincheck:
    pattern: /admin/login_check

trismegiste_logout:
    pattern: /logout
