security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        proprietary:
            id: social.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:   ^/
            provider:  proprietary
            stateless: false
            anonymous: ~
            oauth: 
                login_path:   trismegiste_oauth_connect
                failure_path: trismegiste_oauth_connect
                check_path:   trismegiste_oauth_check
                remember_me:  true
            remember_me:
                always_remember_me: false
                key: %secret%
            logout:
                path:   trismegiste_oauth_logout
                target: /

    access_control:
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
